#!/bin/bash
# vi: ts=4 expandtab
# Package
PACKAGE="minio"
DNAME="minio"

TEMP_STORAGE_DIR="${SYNOPKG_TEMP_UPGRADE_FOLDER}"
INSTALL_DIR="/usr/local/${PACKAGE}"
APP_DIR="${INSTALL_DIR}/minio"
SSS="/var/packages/${DNAME}/scripts/start-stop-status"
PATH="${INSTALL_DIR}:${PATH}"

SERVICETOOL="/usr/syno/bin/servicetool"
FWPORTS="/var/packages/${DNAME}/scripts/${PACKAGE}.sc"

FILE_CREATE_LOG="${APP_DIR}/wizard_create_log"
LOG_FILE="/var/log/minio.log"
PACKAGE_LOG="/var/log/synopkg.log"

preinst ()
{
    exit 0
}

postinst ()
{
    # Link
    ln -s ${SYNOPKG_PKGDEST} ${INSTALL_DIR}

    if [[ "${MINIO_ACCESS_KEY}x" != "x" && "${MINIO_SECRET_KEY}x" != "x" ]]; then
		cat > ${APP_DIR}/config <<EOF
MINIO_PORT=${MINIO_PORT:-9901}
MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-admin}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-$(openssl rand -hex 12)}
EOF
        cat ${APP_DIR}/config >> ${PACKAGE_LOG}
	fi

    # Add firewall config
    ${SERVICETOOL} --install-configure-file --package ${FWPORTS} >> /dev/null

    exit 0
}

preuninst ()
{
    # Stop the package
    ${SSS} stop > /dev/null

    # Remove firewall config
    if [ "${SYNOPKG_PKG_STATUS}" == "UNINSTALL" ]; then
        ${SERVICETOOL} --remove-configure-file --package ${PACKAGE}.sc >> /dev/null
    fi

    exit 0
}

postuninst ()
{
    # Remove link
    rm -f ${INSTALL_DIR}

    # remove log file
    rm -f ${LOG_FILE}

    exit 0
}

preupgrade ()
{
    # Stop the package
    ${SSS} stop > /dev/null
    exit 0
}

postupgrade ()
{
   exit 0
}

log ()
{
    msg=$1
    version=$2
    echo "$(date +"%Y/%m/%d %T") upgrade minio $version $msg" >> ${PACKAGE_LOG}
}

logBegin ()
{
    msg=$1
    version=$2
    echo "$(date +"%Y/%m/%d %T") upgrade minio $version Begin $msg" >> ${PACKAGE_LOG}
}

logEnd ()
{
   msg=$1
   code=$2
   version=$3
   echo "$(date +"%Y/%m/%d %T") upgrade minio $version End $msg ret=[$code]" >> ${PACKAGE_LOG}
}
