#!/bin/bash
#
# with WIZARD_FILES select log file or not
#

# Package
PACKAGE="minio"
DNAME="minio"

# Others
INSTALL_DIR="/usr/local/${PACKAGE}"
DIR_minio="${INSTALL_DIR}/minio"
minio="${DIR_minio}/minio"
PID_FILE="${DIR_minio}/minio.pid"
LOG_FILE="${DIR_minio}/minio.log"

FILE_CREATE_LOG="${DIR_minio}/wizard_create_log"

export HOME=${DIR_minio}
export USER=minio
export USERNAME=minio

start_daemon ()
{
    cd ${DIR_minio}
    mkdir -p ${DIR_minio}/data

    source  ${DIR_minio}/config || \
        echo "Unable to find configuration" > ${LOG_FILE};

    if [ "${MINIO_ACCESS_KEY}x" != "x" ]; then
        export MINIO_ACCESS_KEY
    fi

    if [ "${MINIO_SECRET_KEY}x" != "x" ]; then
        export MINIO_SECRET_KEY
    fi

    ${minio} server data --address 0.0.0.0:${MINIO_PORT:-9901} >> ${LOG_FILE} 2>&1 &
    echo $! > ${PID_FILE}
}

stop_daemon ()
{
    kill `cat ${PID_FILE}`
    wait_for_status 1 20 || kill -9 `cat ${PID_FILE}`
    rm -f ${PID_FILE}
}

daemon_status ()
{
    if [ -f ${PID_FILE} ] && kill -0 `cat ${PID_FILE}` > /dev/null 2>&1; then
        return
    fi
    rm -f ${PID_FILE}
    return 1
}

wait_for_status ()
{
    counter=$2
    while [ ${counter} -gt 0 ]; do
        daemon_status
        [ $? -eq $1 ] && return
        let counter=counter-1
        sleep 1
    done
    return 1
}


case $1 in
    start)
        if daemon_status; then
            echo ${DNAME} is already running
        else
            echo Starting ${DNAME} ...
            start_daemon
        fi
        ;;
    stop)
        if daemon_status; then
            echo Stopping ${DNAME} ...
            stop_daemon
        else
            echo ${DNAME} is not running
        fi
        ;;
    restart)
        stop_daemon
        start_daemon
        ;;
    status)
        if daemon_status; then
            echo ${DNAME} is running
            exit 0
        else
            echo ${DNAME} is not running
            exit 1
        fi
        ;;
    log)
        echo ${LOG_FILE}
        ;;
    *)
        exit 1
        ;;
esac
